version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zima_data
    environment:
      POSTGRES_PASSWORD: 195375AsD+
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5433:5432

  redis:
    image: redis:7
    container_name: zima_redis


  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf # если есть конфиг, иначе можно убрать
    networks:
      - my_network

  zima:
    build:
      context: .
    image: zima_image2
    restart: always
    container_name: zima_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
      - rabbitmq
    command: sh -c "alembic upgrade head && gunicorn zimaApp.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000
    networks:
      - my_network

  celery:
    build:
      context: .
    image: zima_celery # или оставьте как есть, если билд из того же контекста
    container_name: zima_celery
    env_file:
      - .env-non-dev
    depends_on:
      - redis
      - rabbitmq
    command: sh -c "celery --app=zimaApp.tasks.celery_app:celery_app worker -l INFO & celery --app=zimaApp.tasks.celery_app:celery_app beat -l INFO"
    networks:
      - my_network

  flower:
    build:
      context: .
    image: zima_flower # или оставьте как есть, если билд из того же контекста
    container_name: zima_flower
    env_file:
      - .env-non-dev
    depends_on:
      - redis
      - rabbitmq
    command: sh -c "celery --app=zimaApp.tasks.celery_app:celery_app flower"
    ports:
      - 5555:5555
    networks:
      - my_network

volumes:
  postgresdata:
  rabbitmq_data:

networks:
  my_network: