"""изменение имени колонок wells_repair2

Revision ID: 190a36b157e7
Revises: 5988e13a60a8
Create Date: 2025-05-19 10:14:54.609344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '190a36b157e7'
down_revision: Union[str, None] = '5988e13a60a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('well_classifier', 'well_area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('wells_data', 'well_area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('wells_repairs', 'expected_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('wells_repairs', 'curator',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('wells_repairs', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('wells_silencing', 'well_area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wells_silencing', 'well_area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wells_repairs', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wells_repairs', 'curator',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wells_repairs', 'expected_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('wells_data', 'well_area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('well_classifier', 'well_area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
