"""Initial well_clasifier migrate2

Revision ID: 2437d045e7cf
Revises: 7bc9081e9c76
Create Date: 2025-05-02 15:10:12.726205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2437d045e7cf'
down_revision: Union[str, None] = '7bc9081e9c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_user', sa.String(), nullable=False),
    sa.Column('name_user', sa.String(), nullable=False),
    sa.Column('surname_user', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('costumer', sa.String(), nullable=False),
    sa.Column('contractor', sa.String(), nullable=False),
    sa.Column('ctcrs', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wells_silencing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_number', sa.String(), nullable=False),
    sa.Column('deposit_area', sa.String(), nullable=False),
    sa.Column('today', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('costumer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wells_silencing')
    op.drop_table('users')
    # ### end Alembic commands ###
