"""Данные по repais_gis

Revision ID: 3aa7ca706f35
Revises: fd5729db5f23
Create Date: 2025-07-22 14:09:40.125489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3aa7ca706f35"
down_revision: Union[str, None] = "fd5729db5f23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repair_gis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("well_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("contractor_gis", sa.String(), nullable=False),
        sa.Column("message_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("downtime_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("downtime_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("downtime_duration", sa.Float(), nullable=True),
        sa.Column("downtime_reason", sa.String(), nullable=True),
        sa.Column("work_goal", sa.String(), nullable=True),
        sa.Column("contractor_opinion", sa.String(), nullable=True),
        sa.Column("downtime_duration_meeting_result", sa.Float(), nullable=True),
        sa.Column("meeting_result", sa.String(), nullable=True),
        sa.Column("image_pdf", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_repair_gis_id"), "repair_gis", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repair_gis_id"), table_name="repair_gis")
    op.drop_table("repair_gis")
    # ### end Alembic commands ###
