"""Initial wells_data

Revision ID: 3bbb58a9046e
Revises: bbf0e0c00cd0
Create Date: 2025-05-08 10:25:12.113945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbb58a9046e'
down_revision: Union[str, None] = 'bbf0e0c00cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wells_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_number', sa.String(), nullable=False),
    sa.Column('area_well', sa.String(), nullable=False),
    sa.Column('well_oilfield', sa.String(), nullable=False),
    sa.Column('cdng', sa.String(), nullable=False),
    sa.Column('costumer', sa.String(), nullable=True),
    sa.Column('inventory_number', sa.String(), nullable=True),
    sa.Column('wellhead_fittings', sa.String(), nullable=True),
    sa.Column('appointment', sa.String(), nullable=True),
    sa.Column('angle_data', sa.JSON(), nullable=True),
    sa.Column('column_direction', sa.JSON(), nullable=True),
    sa.Column('column_conductor', sa.JSON(), nullable=True),
    sa.Column('column_production', sa.JSON(), nullable=True),
    sa.Column('column_additional', sa.JSON(), nullable=True),
    sa.Column('bottom_hole_drill', sa.Float(), nullable=True),
    sa.Column('bottom_hole_artificial', sa.Float(), nullable=True),
    sa.Column('max_angle', sa.Float(), nullable=True),
    sa.Column('distance_from_rotor_table', sa.Float(), nullable=True),
    sa.Column('max_angle_depth', sa.Float(), nullable=True),
    sa.Column('max_expected_pressure', sa.Float(), nullable=True),
    sa.Column('max_admissible_pressure', sa.Float(), nullable=True),
    sa.Column('rotor_altitude', sa.Float(), nullable=True),
    sa.Column('perforation', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('nkt_data', sa.JSON(), nullable=True),
    sa.Column('sucker_pod', sa.JSON(), nullable=True),
    sa.Column('diameter_doloto_ek', sa.Float(), nullable=True),
    sa.Column('last_pressure_date', sa.Date(), nullable=True),
    sa.Column('date_commissioning', sa.Date(), nullable=True),
    sa.Column('date_drilling_run', sa.Date(), nullable=True),
    sa.Column('date_drilling_finish', sa.Date(), nullable=True),
    sa.Column('geolog', sa.String(), nullable=True),
    sa.Column('date_create', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wells_data')
    # ### end Alembic commands ###
