"""change status2

Revision ID: 42d32bc52ec7
Revises: d9ae2a89b68b
Create Date: 2025-08-07 16:44:57.384284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d32bc52ec7'
down_revision: Union[str, None] = 'd9ae2a89b68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brigade_summary', sa.Column('repair_time_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'brigade_summary', 'repair_times', ['repair_time_id'], ['id'])
    op.drop_constraint('repair_times_brigade_summary_id_fkey', 'repair_times', type_='foreignkey')
    op.drop_column('repair_times', 'brigade_summary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_times', sa.Column('brigade_summary_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('repair_times_brigade_summary_id_fkey', 'repair_times', 'brigade_summary', ['brigade_summary_id'], ['id'])
    op.drop_constraint(None, 'brigade_summary', type_='foreignkey')
    op.drop_column('brigade_summary', 'repair_time_id')
    # ### end Alembic commands ###
