"""изменение имени колонок

Revision ID: 5988e13a60a8
Revises: bca7c829aca2
Create Date: 2025-05-16 10:31:40.083055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5988e13a60a8'
down_revision: Union[str, None] = 'bca7c829aca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well_classifier', sa.Column('well_area', sa.String(), nullable=True))
    op.drop_column('well_classifier', 'deposit_area')
    op.add_column('wells_data', sa.Column('well_area', sa.String(), nullable=True))
    op.drop_column('wells_data', 'area_well')
    op.alter_column('wells_repairs', 'expected_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('wells_repairs', 'curator',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wells_repairs', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('wells_silencing', sa.Column('well_area', sa.String(), nullable=True))
    op.drop_column('wells_silencing', 'deposit_area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wells_silencing', sa.Column('deposit_area', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('wells_silencing', 'well_area')
    op.alter_column('wells_repairs', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wells_repairs', 'curator',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wells_repairs', 'expected_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('wells_data', sa.Column('area_well', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('wells_data', 'well_area')
    op.add_column('well_classifier', sa.Column('deposit_area', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('well_classifier', 'well_area')
    # ### end Alembic commands ###
