"""add column classifica

Revision ID: 60512616193a
Revises: 7a4ee4421996
Create Date: 2025-08-12 08:48:37.422342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60512616193a'
down_revision: Union[str, None] = '7a4ee4421996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well_classifier', sa.Column('wellhead_pressure', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well_classifier', 'wellhead_pressure')
    # ### end Alembic commands ###
