"""Данные по нормам и бригад2

Revision ID: 6b699adf6b5c
Revises: 0d65ce5fc5ff
Create Date: 2025-06-09 11:17:15.419170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b699adf6b5c'
down_revision: Union[str, None] = '0d65ce5fc5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brigade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor', sa.String(), nullable=False),
    sa.Column('costumer', sa.String(), nullable=False),
    sa.Column('expedition', sa.String(), nullable=False),
    sa.Column('number_brigade', sa.Integer(), nullable=False),
    sa.Column('brigade_master', sa.JSON(), nullable=False),
    sa.Column('phone_number_brigade', sa.String(), nullable=False),
    sa.Column('lifting_unit', sa.String(), nullable=False),
    sa.Column('hydraulic_wrench', sa.String(), nullable=False),
    sa.Column('weight_indicator', sa.String(), nullable=False),
    sa.Column('brigade_composition', sa.JSON(), nullable=True),
    sa.Column('pvo_type', sa.String(), nullable=False),
    sa.Column('number_pvo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number_brigade')
    )
    op.create_table('norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=True),
    sa.Column('start_well_repair', sa.DateTime(), nullable=False),
    sa.Column('repair_well_repair', sa.DateTime(), nullable=True),
    sa.Column('type_tkrs', sa.String(), nullable=True),
    sa.Column('summary_work', sa.JSON(), nullable=True),
    sa.Column('norms_json', sa.JSON(), nullable=True),
    sa.Column('creater_id', sa.Integer(), nullable=True),
    sa.Column('lifting_unit', sa.String(), nullable=True),
    sa.Column('date_create', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['wells_repairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('norms')
    op.drop_table('brigade')
    # ### end Alembic commands ###
