"""relationship

Revision ID: 7a4ee4421996
Revises: 42d32bc52ec7
Create Date: 2025-08-08 15:15:34.898830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4ee4421996'
down_revision: Union[str, None] = '42d32bc52ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_date_time', 'brigade_summary', ['date_summary', 'time_interval'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_date_time', 'brigade_summary', type_='unique')
    # ### end Alembic commands ###
