"""Initial well_clasifier migrate

Revision ID: 7bc9081e9c76
Revises: 
Create Date: 2025-05-01 12:13:20.738824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc9081e9c76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well_classifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cdng', sa.String(), nullable=False),
    sa.Column('well_number', sa.String(), nullable=False),
    sa.Column('deposit_area', sa.String(), nullable=False),
    sa.Column('oilfield', sa.String(), nullable=True),
    sa.Column('category_pressure', sa.String(), nullable=True),
    sa.Column('pressure_ppl', sa.String(), nullable=True),
    sa.Column('pressure_gst', sa.String(), nullable=True),
    sa.Column('date_measurement', sa.String(), nullable=True),
    sa.Column('category_h2s', sa.String(), nullable=True),
    sa.Column('h2s_pr', sa.String(), nullable=True),
    sa.Column('h2s_mg_l', sa.String(), nullable=True),
    sa.Column('h2s_mg_m', sa.String(), nullable=True),
    sa.Column('category_gf', sa.String(), nullable=True),
    sa.Column('gas_factor', sa.String(), nullable=True),
    sa.Column('today', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('costumer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('well_classifier')
    # ### end Alembic commands ###
