"""'Добавление

Revision ID: 8f82fa9dd73d
Revises: 
Create Date: 2025-05-14 23:28:49.235351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f82fa9dd73d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gnkt_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gnkt_number', sa.String(), nullable=False),
    sa.Column('well_number', sa.String(), nullable=False),
    sa.Column('well_area', sa.String(), nullable=False),
    sa.Column('contractor', sa.String(), nullable=False),
    sa.Column('length_gnkt', sa.Integer(), nullable=False),
    sa.Column('diameter_gnkt', sa.Float(), nullable=False),
    sa.Column('wear_gnkt', sa.Float(), nullable=False),
    sa.Column('mileage_gnkt', sa.String(), nullable=False),
    sa.Column('tubing_fatigue', sa.Float(), nullable=False),
    sa.Column('previous_well', sa.String(), nullable=False),
    sa.Column('date_repair', sa.Date(), nullable=False),
    sa.Column('pvo_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('wells_repairs', sa.Column('perforation_project', sa.JSON(), nullable=True))
    op.add_column('wells_repairs', sa.Column('type_absorbent', sa.String(), nullable=True))
    op.add_column('wells_repairs', sa.Column('dinamic_level', sa.Float(), nullable=True))
    op.add_column('wells_repairs', sa.Column('expected_data', sa.JSON(), nullable=True))
    op.add_column('wells_repairs', sa.Column('curator', sa.String(), nullable=True))
    op.add_column('wells_repairs', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wells_repairs', 'region')
    op.drop_column('wells_repairs', 'curator')
    op.drop_column('wells_repairs', 'expected_data')
    op.drop_column('wells_repairs', 'dinamic_level')
    op.drop_column('wells_repairs', 'type_absorbent')
    op.drop_column('wells_repairs', 'perforation_project')
    op.drop_table('gnkt_data')
    # ### end Alembic commands ###
