"""brigade number is string

Revision ID: a4469e3e8995
Revises: 60512616193a
Create Date: 2025-08-15 10:57:04.865032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4469e3e8995'
down_revision: Union[str, None] = '60512616193a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brigade', 'number_brigade',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('uix_date_time', 'brigade_summary', type_='unique')
    op.create_unique_constraint('uix_date_time', 'brigade_summary', ['date_summary', 'time_interval', 'repair_time_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_date_time', 'brigade_summary', type_='unique')
    op.create_unique_constraint('uix_date_time', 'brigade_summary', ['date_summary', 'time_interval'])
    op.alter_column('brigade', 'number_brigade',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
