"""summary act_path ARRAY

Revision ID: e09ed95a9987
Revises: a4469e3e8995
Create Date: 2025-08-15 12:18:00.896891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09ed95a9987'
down_revision: Union[str, None] = 'a4469e3e8995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brigade_summary', 'act_path',
               existing_type=sa.TEXT(),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brigade_summary', 'act_path',
               existing_type=sa.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
