"""add brigade_info_date

Revision ID: ee785eed9a37
Revises: cc61896aec70
Create Date: 2025-06-11 11:13:47.724056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee785eed9a37"
down_revision: Union[str, None] = "cc61896aec70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("norms", sa.Column("date_create", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("norms", "date_create")
    # ### end Alembic commands ###
