"""add brigade_info

Revision ID: f31f06340677
Revises: 6b699adf6b5c
Create Date: 2025-06-09 18:19:54.513675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31f06340677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('norms', 'date_create')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('norms', sa.Column('date_create', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
