"""add summary2

Revision ID: f68506d646b5
Revises: c865458be31b
Create Date: 2025-08-07 10:47:20.787101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f68506d646b5'
down_revision: Union[str, None] = 'c865458be31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brigade_summary', sa.Column('date_summary', sa.Date(), nullable=False))
    op.add_column('brigade_summary', sa.Column('photo_path', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('brigade_summary', 'date')
    op.drop_column('brigade_summary', 'foto_path')
    op.alter_column('repair_times', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('repair_times', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repair_times', 'end_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('repair_times', 'start_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('brigade_summary', sa.Column('foto_path', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('brigade_summary', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('brigade_summary', 'photo_path')
    op.drop_column('brigade_summary', 'date_summary')
    # ### end Alembic commands ###
